[package]
name = "lmdb-rust"
version = "0.1.0"
authors = ["Alexander Tesfamichael <alex.tesfamichael@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
